server:
  port: 9000

spring:
  application:
    name: app-gateway-server
  cloud:
    gateway:
      routes:
      - id: helloModule
#        uri: http://localhost:8081/
        uri: lb://app-hello-service
        predicates:
        - Path=/hello/**
      - id: goodbyeModule
#        uri: http://localhost:8082/
        uri: lb://app-bye-service
        predicates:
        - Path=/bye/**
      
      - id: helloworldModule
#        uri: http://localhost:9001/
        uri: lb://app-loadbalancer
        predicates:
        - Path=/helloworld
        filters:
        - RewritePath=/helloworld, /
      - id: byebyeworldModule
#        uri: http://localhost:9002/
        uri: lb://app-loadbalancer2
        predicates:
        - Path=/byebyeworld
        filters:
        - RewritePath=/byebyeworld, /
eureka:
  instance:
    hostname: localhost
  client:
    service-url: 
      defaultZone : http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# gateway 노출    
management:
  endpoints:
    web:
      exposure:
        include: 'gateway'