# app-config-client
server:
  port: 8089
spring:
  application:
    name: app-config-client
  cloud:
    config: # Ex) `http://localhost:8888/myconfig/test`
      name: myconfig # 위의 경로에서 myconfig경로
      profile: test # 위의 경로에서 마지막 test => github에 있는 myconfig-test.properties파일 가져올
  config:
    import: optional:configserver:http://localhost:8888
    
# 설정값 refresh
management:
  endpoints:
    web:
      exposure:
        include: ['env', 'refresh'] # POST http://{service_url}/actuator/refresh 호출


